### PR TITLE
Increase allowed length of TLD part of the mail

### PR DESCRIPTION
**Pull request by DBX12**
Removed the upper limit of 4 characters for the TLD part of the email.

### CODE REVIEW

**Comment by Mokto** [comment]
That's fine with me. Thanks !

**Comment by Mokto** [comment]
Could you name your commit : `feat: increase allowed length of TLD part of the mail` please ?

So that your work goes to release notes.

**Comment by DBX12** [comment]
I will rename the commit tomorrow (or so) because my current PC does not have GIT installed. Or is there a way to modify it over the GitHub website?

**Comment by Mokto** [comment]
I don't think so. No hurry !

**Comment by DBX12** [comment]
Something went really wrong on my fork, not sure what but suddenly a whole bunch of identical commits appeared here. I file a new PR to prevent cluttering up the commit history.

Edit: #357 shall be the new PR

**Pull request closed without merging**
